apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidal-casino-frontend
  labels:
    app: vidal-casino-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vidal-casino-frontend
  template:
    metadata:
      labels:
        app: vidal-casino-frontend
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: vidal-casino-frontend

      containers:
        - name: vidal-casino-frontend
          image: 631932931672.dkr.ecr.us-east-1.amazonaws.com/vidal-casino-frontend:latest
          ports:
            - containerPort: 80      
          env:
            - name: BACKEND_HOST
              value: "backend-service"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  ports:
    - port: 80                    
      targetPort: 80        
  selector:
    app: vidal-casino-frontend