name: Build & Deploy frontend

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar credenciales AWS (temporales del Learner Lab)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_REGION }}
          
      - id: ecr
        name: Login a ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Build & push frontend
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
        run: |
          IMAGE=$REGISTRY/casino-frontend
          docker build -t $IMAGE:${{ github.sha }} -t $IMAGE:latest .
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest

      - name: Actualizar Kubeconfig para Amazon EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name vidal-casino-cluster

      - name: Desplegar Frontend en EKS con Kubectl
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          
          kubectl rollout restart deployment/casino-frontend